name: Build PR

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Install
        run: mvn clean install -DskipTests=true

  test-jdbc:
    name: Test (flink-connector-oceanbase)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Test
        run: mvn verify -pl :flink-connector-oceanbase
