name: Build PR

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Install
        run: mvn clean install -DskipTests=true

  test-flink-connector-oceanbase:
    name: Test (flink-connector-oceanbase)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Test
        run: |
          cd flink-connector-oceanbase
          mvn verify

  test-flink-connector-obkv-hbase:
    name: Test (flink-connector-obkv-hbase)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Test
        run: |
          cd flink-connector-obkv-hbase
          mvn verify
