name: Build Main

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Build
        run: mvn clean verify -DskipTests=true

  test-flink-connector-oceanbase:
    name: Test (flink-connector-oceanbase)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Test
        run: mvn verify -pl :flink-connector-oceanbase -am

  test-flink-connector-obkv-hbase:
    name: Test (flink-connector-obkv-hbase)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'
          cache: 'maven'
      - name: Maven Test
        run: mvn verify -pl :flink-connector-obkv-hbase -am
